### PR TITLE
Auto funding script

### PR DESCRIPTION
**Pull request by StefanIliev545**
### Why this change is needed

Please provide a description and a link to the underlying ticket

### What changes were made as part of this PR

Please provide a high level list of the changes made

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/obscuronet/obscuro-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

### CODE REVIEW

**Review by BedrockSquirrel — COMMENTED** [review]
LGTM from my mediocre hardhat understanding. Need to drop the SQL fix commit from the branch though I guess.

**Review by tudor-malene — COMMENTED** [review]
there's commit in here that don't belong.
It should be rebased on main

**Comment by StefanIliev545** [comment]
> there are commits in here that don't belong in this PR. It should be rebased on main

I've had the gas fixes here merged as I needed it to debug stuff, does it need a rebase now that the other one is in?

**Review by BedrockSquirrel — APPROVED** [review]
LGTM - except maybe getting rid of that 0.9 * tx size thing in the gas calculation we talked about. Bit weird bout the wait for receipts not working too but given that's just sim code I guess is fine for now. Excited to get this one in with the simple transfer to bridge ability 💪

**Pull request merged**
