### PR TITLE
Obscuroscan v2 deploy 

### PR DESCRIPTION
**Pull request by otherview**
### Why this change is needed

https://github.com/obscuronet/obscuro-internal/issues/1958

### What changes were made as part of this PR

- Adds a dockerfile for obscuroscan
- Adds a manual trigger to deploy it to azure

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/obscuronet/obscuro-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

### CODE REVIEW

**Comment by moraygrieve** [comment]
Is the intention is to have the v2 in parallel to the current implementation, and then when complete remove the old one?

**Comment by otherview** [comment]
> Is the intention is to have the v2 in parallel to the current implementation, and then when complete remove the old one?

Yep, that is correct!

**Review by BedrockSquirrel — APPROVED** [review]
Looks reasonable to me, don't know about the port numbers but guess you can figure that all out when we're productionising. Looks like atm it's exposing FE on 81 and backend on 82 from the VM?

**Comment by otherview** [comment]
> Looks reasonable to me, don't know about the port numbers but guess you can figure that all out when we're productionising. Looks like atm it's exposing FE on 81 and backend on 82 from the VM?

Yes, when you run it "locally" the FE takes port 81 and BE 82, that's because the faucet is already taking port 80 in the local testnet launcher.

**Pull request merged**
