### PR TITLE
fix test ports

### PR DESCRIPTION
**Pull request by otherview**
### Why this change is needed

Seems to be a collision on the ports assigned to some of the tests

### What changes were made as part of this PR

Please provide a high level list of the changes made

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/obscuronet/obscuro-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

### CODE REVIEW

**Review by BedrockSquirrel — COMMENTED** [review]
I agree this looks like a problem because it's using the same port range as the wallet ext unit test constant but I'm not sure this reliably fixes it because both the tests in `contract_deployer_test` call `createObscuroNetwork` with a start port which then has offsets like `DefaultEnclaveOffset` (which are multiples of 100) added to it. So instead of creating two networks from 39000-39999 and 40000-40999, it now does them from 39000-39999 and 39100-40099.

**Comment by otherview** [comment]
@coderabbitai pause

**Comment by otherview** [comment]
> I agree this looks like a problem because it's using the same port range as the wallet ext unit test constant but I'm not sure this reliably fixes it because both the tests in `contract_deployer_test` call `createObscuroNetwork` with a start port which then has offsets like `DefaultEnclaveOffset` (which are multiples of 100) added to it. So instead of creating two networks from 39000-39999 and 40000-40999, it now does them from 39000-39999 and 39100-40099.

Good point - after some digging I removed the `_portOffset` as it's not doing anything because tests inside the same `_test.go` run sequentially by default.

**Review by BedrockSquirrel — APPROVED** [review]
lgtm

**Pull request merged**
