### PR TITLE
flatten project structure

### PR DESCRIPTION
**Pull request by tudor-malene**
### Why is this change needed?

The project structure has evolved from a simulation and it didn't reflect the current needs too well

### What changes were made as part of this PR:

- refactoring PR 

1. All the common stuff is now in "common".
2. The host and enclave are now top-level. Together with the wallet, the eth_adapter and the rpc_client_lib

### What are the key areas to look at
- the structure

### CODE REVIEW

**Comment by joeldudley** [comment]
@tudor-malene The instructions in `rpc/generated/readme` are out of date now. It says, `cd go/obscuronode/nodecommon/rpc/generated`.

**Comment by joeldudley** [comment]
@tudor-malene I think the `common` folder needs a subpackage for stuff that's shared across the host and enclave, with an informative name.

**Comment by tudor-malene** [comment]
> nodecommon

thanks. good point

**Comment by tudor-malene** [comment]
> @tudor-malene I think the `common` folder needs a subpackage for stuff that's shared across the host and enclave, with an informative name.

how is that different from the other common stuff?

**Comment by joeldudley** [comment]
@tudor-malene This also breaks the commands on lines 31-35 of `tools/azuredeployer/networkdeployer/network_deployer.go`.

**Review by joeldudley — CHANGES_REQUESTED** [review]
Happy to merge, subject to my comments. Think we'll have missed a few things, but impossible to foresee everything.

**Comment by tudor-malene** [comment]
> > > @tudor-malene I think the `common` folder needs a subpackage for stuff that's shared across the host and enclave, with an informative name.
> > 
> > 
> > how is that different from the other common stuff?
> 
> The `log` package is used everywhere, not just host and enclave. Similar to `httputil` eventually, could be used more broadly.
> 
> I guess I'm expressing the view that the top level of the `common` module seems like a dumping ground atm. Maybe one to fix later?

these things tend to fall into place at their own time. I think it's better to keep it less structured until something emerges.

**Review by joeldudley — APPROVED** [review]
LGTM

**Pull request merged**
