### PR TITLE
Added tasks for the wallet extension.

### PR DESCRIPTION
**Pull request by StefanIliev545**
### Why is this change needed?

- Provide a description and a link to the underlying ticket

### What changes were made as part of this PR:

- Provide a high level list of the changes made

### Definition of done

- [ ] Unit tests added to cover new or changed functionality 
- [ ] Docs pages updated to cover new or changed functionality
- [ ] [Changelog.md](https://github.com/obscuronet/go-obscuro/blob/main/docs/testnet/changelog.md) updated 
- [ ] End-to-end tests run if required (see below)

### End-to-end tests

Running the end-to-end tests in the [obscuro-test repo](https://github.com/obscuronet/obscuro-test) is currently at the 
discretion of the developer prior to merging a PR. The intention is not to slow down development by having the longer 
running end-to-end tests as a PR gate run on each branch commit etc. To manually trigger a run pre-merge;

- Go to [run_local_tests](https://github.com/obscuronet/obscuro-test/actions/workflows/run_local_tests.yml)
- Click the "Run workflow" button
- Use the main branch of obscuro-test 
- Enter the name of the PR branch for go-obscuro
- Run the workflow

The run takes approximately 20 minutes and any failure will be reported in the workflow output. Should the tests fail 
the docker container output for the local testnet and all test artifacts will be added to the run and can be downloaded
for debugging and analysis, with a retention period of 2 days. 

Note that every PR merge to main will also trigger a run of post-merge tests, so even if you do not manually trigger 
pre-merge, tests will be run post-merge. The intention being to catch any issues fast on main to allow for quick 
resolution. The post-merge test output can be seen at 
[run_merge_tests](https://github.com/obscuronet/obscuro-test/actions/workflows/run_merge_tests.yml) and will show both 
the PR number and author in the list of runs.

### CODE REVIEW

**Review by tudor-malene — APPROVED** [review]
LGTM.
maybe @otherview can have a look as well

**Review by otherview — COMMENTED** [review]
Why allow Hardhat to orchestrate the wallet extension ? Or in other words, do we want to tie HardHat and the download/build/launch of a docker image together ?
Similarly, hardhat does not orchestrate starting an Ethereum node. It only takes an address and it's blind to anything else.
Implicitly it seems to enforce the need for docker, docker build / docker get, to be done by the task user.

Maybe a simpler scope of HH to register/manage the communication/ VK register with the WE could make these less coupled while providing a lot of help in dev usage ?

**Comment by StefanIliev545** [comment]
> Why allow Hardhat to orchestrate the wallet extension ? Or in other words, do we want to tie HardHat and the download/build/launch of a docker image together ? Similarly, hardhat does not orchestrate starting an Ethereum node. It only takes an address and it's blind to anything else. Implicitly it seems to enforce the need for docker, docker build / docker get, to be done by the task user.
> 
> Maybe a simpler scope of HH to register/manage the communication/ VK register with the WE could make these less coupled while providing a lot of help in dev usage ?

Docker should automatically pull the image when doing `docker run` if it's not available. IMO it makes sense for hardhat to manage the wallet extension from the perspective of ultimately wanting those bits to be extracted as a plugin; 
Hardhat doesn't manage an ethereum node if the network is external, but it still has the integrated one for convenience. Ultimately the end game for the plugin I see is the same - hardhat obscuro:test - spawns wallet extension, hardhat test does not. While we can do it with bash scripts on the CI, they don't make for the greatest UX when doing stuff manually.

**Comment by otherview** [comment]
It's not about scripts. HH is the orchestrator when it's only required for it to be the client of the WE.
At some stage, we had the simulation run on docker too, but we've since backed away from it.

On one hand, we're making the HH coupled with the docker app and docker build image.
And on the other hand instead of starting a wallet and leaving it running while operations are being done, now we need to be weary that HH might start a new wallet.

We can probably change that once we identify the need for a specific HH plugin, but I don't think that's a need atm.

All of that said. I am happy to merge this IF we agree to use this as a dev utility.

**Pull request merged**
