### PR TITLE
Wallet extension to default to testnet

### PR DESCRIPTION
**Pull request by tudor-malene**
### Why is this change needed?

To make it easier for users trying out testnet
See: https://github.com/obscuronet/obscuro-internal/issues/701

Also, added small doc improvements

### What changes were made as part of this PR:

Functional PR
-change default value to testnet
- add instruction to add JAM token 
- other small doc clarifiations

### CODE REVIEW

**Comment by joeldudley** [comment]
I think we can drop the flags here now: https://docs.obscu.ro/testnet/deploying-a-smart-contract.html#prepare-your-metamask-wallet-for-obscuro-testnet. Defaults should be fine.

Also, defaults described here are wrong now: https://docs.obscu.ro/wallet-extension/wallet-extension.html.

**Comment by moraygrieve** [comment]
LGTM but requires changes as Joel mentioned (it did used to default to testnet but AFAIR was changed to local host recently?)

**Review by moraygrieve — CHANGES_REQUESTED** [review]
LGTM but requires changes as per Joel's comments.

**Comment by tudor-malene** [comment]
> LGTM but requires changes as per Joel's comments.

Thanks @moraygrieve . I've updated them.
@joeldudley , back to you

**Comment by tudor-malene** [comment]
@moraygrieve , made the change spotted by @joeldudley .

**Review by moraygrieve — APPROVED** [review]
LGTM

**Pull request merged**
