### PR TITLE
Update testnet-kpis.md

### PR DESCRIPTION
**Pull request by GavT**
### Why is this change needed?

- Update to KPI source for "dApps in development"

### What changes were made as part of this PR:

- Text change

### :rotating_light: Definition of done :rotating_light:
- [ ] Unit tests added to cover new or changed functionality 
- [ ] Docs pages updated to cover new or changed functionality
- [ ] [Changelog.md](https://github.com/obscuronet/go-obscuro/blob/main/docs/testnet/changelog.md) updated

### CODE REVIEW

**Review by tooward — COMMENTED** [review]
- "LOI/MOU signed" - wasn't aware this is a part of our process. I'd like to know if this is necessary / typical for L2s before we put it as a metric that we measure ourselves against.
- Feels like we need to list anything that is a functional Dapp on Testnet on a webpage so others can use them when needed (ex: DEX). Maybe that is how we can measure it? As James noted, figuring out deployments is going to become an engineering task if we go the address route.
- Why is end user accounts needed if we are measuring wallet extension downloads? Measures same thing.

**Comment by CaisManai** [comment]
> * Why is end user accounts needed if we are measuring wallet extension downloads? Measures same thing.

It measures conversion i.e. if a user downloads the wallet, will they run it? If we see a disparity between the two we'll know users don't trust the binary

**Comment by GavT** [comment]
> * "LOI/MOU signed" - wasn't aware this is a part of our process. I'd like to know if this is necessary / typical for L2s before we put it as a metric that we measure ourselves against.

Yeah, this would just add friction.

**Comment by GavT** [comment]
> * Feels like we need to list anything that is a functional Dapp on Testnet on a webpage so others can use them when needed (ex: DEX). Maybe that is how we can measure it? As James noted, figuring out deployments is going to become an engineering task if we go the address route.

There is something in the backlog to do this, but its non trivial to get it right. I expect this will become the data source for the KPI  of "new dApps deployed on testnet".

**Comment by tooward** [comment]
> > * Why is end user accounts needed if we are measuring wallet extension downloads? Measures same thing.
> 
> It measures conversion i.e. if a user downloads the wallet, will they run it? If we see a disparity between the two we'll know users don't trust the binary

Yes, but my point is we need fewer metrics we actually review and change our behavior based on. This is a nuance. As a 
product person I agree you should look at this. For reporting in general two measures that capture a nuance won't be understood. KISS

**Comment by tooward** [comment]
> > * Feels like we need to list anything that is a functional Dapp on Testnet on a webpage so others can use them when needed (ex: DEX). Maybe that is how we can measure it? As James noted, figuring out deployments is going to become an engineering task if we go the address route.
> 
> There is something in the backlog to do this, but its non trivial to get it right. I expect this will become the data source for the KPI of "new dApps deployed on testnet".

What is in the backlog? Website (simple) or figuring out what are non-owned accounts? Website pays in two ways - your metric and a better visual for anyone checking us out. I'd just use the website and move on.

**Review by CaisManai — APPROVED** [review]

**Pull request merged**
